### ISSUE TITLE
4 year old version of DPDK?

### ISSUE THREAD

**Issue by dtaht** [asterfusion/Helium_DPU#1]
While I am happy to see you doing this, shipping a 4 year old version of the dpdk does not help your cause. When will this be supported by mainline dpdk?

**Comment by Aster-Marvin** [comment]
we will add dpdk 20.11/21.11 later. The mainline dpdk will add to our milestone, thank you for your option.

**Comment by Aster-Marvin** [comment]
we have update the dpdk version to 24.03, and will follow the master, will clost it.
