### ISSUE TITLE
Host Driver Compilation Error

### ISSUE THREAD

**Issue by Kryptoxic** [asterfusion/Helium_DPU#2]
**Describe the bug**
When compiling the host driver for the DPU, the compilation fails.

**To Reproduce**
1. Clone the repo using command "git clone https://github.com/asterfusion/Helium_DPU"
2. Navigate to the Host drivers folder "cd Helium_DPU/Host/Drivers"
3. Compile using command "make"
4. Error appears halfway through compilation

**Expected behavior**
The compilation of the host drivers are successful.

**Screenshots**
![image](https://github.com/asterfusion/Helium_DPU/assets/15937274/886c6ecf-351c-4132-ba41-7bc1d2fbf647)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu Server 22.04.2 LTS
 - DPU: Asterfusion Helium EC2002P
 - GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

**Additional context**
When using the Helium-Driver-V1.0R1.tar.gz provided drivers, the drivers are able to be compiled.

**Comment by LIYFei** [comment]
I updated my current GCC version and got the same error. The reason is that in the new version of GCC compilation, the scope of the 'if' statement is unclear. Therefore, I made some modifications and successfully compiled it. commit-id #246a0f451eff6fe67abd1d2706f51df1db08ca2c

**Comment by LIYFei** [comment]
I updated my current GCC version and got the same error. The reason is that in the new version of GCC compilation, the scope of the 'if' statement is unclear. Therefore, I made some modifications and successfully compiled it .commit-id 246a0f4

**Comment by Kryptoxic** [comment]
I will checkout the commit and compile it again on Monday and report back. Thanks for the reply.

**Comment by Kryptoxic** [comment]
The if error has been solved but I am now getting a new error during compilation

![image](https://github.com/asterfusion/Helium_DPU/assets/15937274/2b3c01b2-35a1-4d4b-890d-d887f1ee3ae6)

**Comment by LIYFei** [comment]
Due to the different kernel versions, I have made the corresponding modifications. Please try again.commit-id e82c569

**Comment by Kryptoxic** [comment]
Yes it works now. Thanks for the fix. I will try this new driver with Openstack to see if anything changed for issue #3
